### ISSUE TITLE
api.botUpdate - Multi-Pairs Not Working

### ISSUE THREAD

**Issue by Sfuarf** [rentorm/3commas-api-node#28]
Hi There, 

I am trying to update a bot automatically, I have been able to do this successfully with a single pair bot but now I am trying with a multi-pair bot it will only accept the last value in the list of pairs.

Please see snippet below:

![botUpdate](https://user-images.githubusercontent.com/27626424/154498580-31b579de-7906-485c-9f5f-48808003497c.png)

In this instance, the values for the bot update, but the pairs become only "USDT_ADA".

I have seen mentions about using JSON instead of these arrays, but not sure how I would need to modify the index.js files to make this work?

Any help would be greatly appreciated!

Cheers,

**Comment by vepierrethibaud** [comment]
Hi @Sfuarf , 

Did you find out what was missing here? Thanks

**Comment by Sfuarf** [comment]
Hey @vepierrethibaud,

Yes, I found the solution in another one of the issue threads. I needed to stringify the list as seen below.

`'pairs': JSON.stringify(current_bot_pairs),`

Where 'current_bot_pairs' was the list I was referring to.

Hope that helps.

Cheers,

**Comment by vepierrethibaud** [comment]
Ye I just figured it out too!

Used it for pairs and strategies. 

Thanks
