### ISSUE TITLE
New base endpoint

### ISSUE THREAD

**Issue by lucarosellini** [rentorm/3commas-api-node#4]
According to [3commas official API docs](https://github.com/3commas-io/3commas-official-api-docs), the base endpoint has changed to [https://api.3commas.io/public/api](https://api.3commas.io/public/api).

Could you please update the base endpoint and ship an update of the library?

Thanks

**Comment by rentorm** [comment]
Thanks for letting me know of this update, I've updated the library and published on npm - https://www.npmjs.com/package/3commas-api-node
