### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by kelleryvo** [rentorm/3commas-api-node#5]
With the updated version, 3commas says the signature is not valid anymore for me? Did they also change something about that process?

Object {error: "signature_invalid", error_description: "Provided signature is invalid"}

**Comment by rentorm** [comment]
it was an issue related to path pormat, it was bein passed worngly for hashing. This issue is now corrected.

**Comment by kelleryvo** [comment]
Working fine now! Thanks for taking the time and fixing.
