### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by Rhydderch** [rentorm/3commas-api-node#6]
Hi rentorm,
Do you think it would be possible to create this for R?
As I struggle to use 3commas' API in R, this would be very helpful in fetching my data from 3commas using R scripts. 
Best,
Rhydderch

**Comment by rentorm** [comment]
Hi Rhydderch,
I do not know R language and I work only with JavaScript. Unfortunately I would not be able to help with this.
Hope you can find someone who can help to create R library for it.
