### ISSUE TITLE
Readme update botsUpdate to botUpdate 

### ISSUE THREAD

**Issue by ZoranRavic** [rentorm/3commas-api-node#7]
Readme says to use `botsUpdate`, but the actual api is `botUpdate`

**Comment by rentorm** [comment]
@Amantel would you mind to look at this issue? ;)

**Comment by Amantel** [comment]
Will do :)

**Comment by Amantel** [comment]
@ZoranRavic is right - it should be in singular form, as all other bot functions. I will update the readme.

**Comment by rentorm** [comment]
Excellent, thank you for your contribution!
